module.exports = {
  productUrl: 'https://www.microcenter.com/product/688173/apple-mac-mini-mu9d3ll-a-(late-2024)-desktop-computer',
  stores: [
    { name: 'AZ - Phoenix', id: '205' },
    { name: 'CA - Tustin', id: '101' },
    { name: 'CO - Denver', id: '181' },
    { name: 'GA - Duluth', id: '065' },
    { name: 'GA - Marietta', id: '041' },
    { name: 'IL - Chicago', id: '151' },
    { name: 'IL - Westmont', id: '025' },
    { name: 'KS - Overland Park', id: '191' },
    { name: 'MA - Cambridge', id: '121' },
    { name: 'MD - Rockville', id: '085' },
    { name: 'MD - Parkville', id: '125' },
    { name: 'MI - Madison Heights', id: '055' },
    { name: 'MN - St. Louis Park', id: '045' },
    { name: 'MO - Brentwood', id: '095' },
    { name: 'NJ - North Jersey', id: '075' },
    { name: 'NY - Westbury', id: '171' },
    { name: 'NY - Brooklyn', id: '115' },
    { name: 'NY - Flushing', id: '145' },
    { name: 'NY - Yonkers', id: '105' },
    { name: 'OH - Columbus', id: '141' },
    { name: 'OH - Mayfield Heights', id: '051' },
    { name: 'OH - Sharonville', id: '071' },
    { name: 'PA - St. Davids', id: '061' },
    { name: 'TX - Houston', id: '155' },
    { name: 'TX - Dallas', id: '131' },
    { name: 'VA - Fairfax', id: '081' },
    { name: 'IN - Indianapolis', id: '165' },
    { name: 'NC - Charlotte', id: '175' },
    { name: 'FL - Miami', id: '185' },
    { name: 'CA - Santa Clara', id: '195' },
    { name: 'TX - Austin', id: '215' },
    { name: 'Web Store', id: '029' }
  ],
  checkIntervalCron: '0 9 * * *', // Run daily at 9am
};
